---
- name: Install Docker Engine di semua node
  hosts: all
  become: true
  roles:
    - role: docker_engine

- name: Deploy Backend ke group backend
  hosts: backend
  become: true
  roles:
    - role: backend_deploy
